### ISSUE TITLE
US#01TK#007 Iniciar MVC de backend

### ISSUE THREAD

**Issue by AnibalFlores** [classroomEntreRios/proyecto-g1b-proyecto-g1b#20]
Se actualizó branch **master** con  backend frontend y docs renombrados a **Viajes 365º**
Sobre backend se incluye entidades user y role con sus controllers + postman collections.
Tambien se creo branch **develop** donde se tendra el progreso del proyecto en el sprint, al inicio de cada sprint en lo posible develop pasará a ser master

**Comment by AnibalFlores** [comment]
Especialmente realizado con Visual Studio 2019 proyecto vacio NET Core 5

**Comment by Alexx73** [comment]
Testeado, todo Ok

**Comment by AnibalFlores** [comment]
merged in develop
