### ISSUE TITLE
US#12TK#014 Agregar paginado de listados

### ISSUE THREAD

**Issue by AnibalFlores** [classroomEntreRios/proyecto-g1b-proyecto-g1b#27]
Permitir que las entidades sean consultadas en listados paginados, dicha _**feature**_ a las consultas actuales es **_una mejora a la experiencia de usuario_**. Los GET endpoints, por ejemplo, serán de la forma:

`http://localhost:5000/api/locations?pageNumber=3&pageSize=10`

Debe dar por respuesta hasta 10 elementos de la entidad **Location** en página 3, también para controlar el paginado desde el **client** (frontend) es necesario saber el **total de registros del dataset**, para ello la estructura json debe ser:
```
 {  "totalElements": 30,
    "totalPages": 3,
    "pageNumber": 3,
    "pageSize": 10,
    "listElements":[
              { id: 21, "fulladdress": "San Martin 1234", ...} ,
              {...} ,
              { "id": 29, "fulladdress": "Urquiza 1234", ...}
             ]
 }
```
en el caso de no haber registros se dara el mensaje 
```
{
    "errorCode":  416,
    "message": "NO HAY RESULTADOS CON LOS PARAMETROS INDICADOS"
}
```
Para un ejemplo de **_error codes_** comunes de un **_Rest Api_** ver https://docs.microsoft.com/en-us/rest/api/storageservices/common-rest-api-error-codes

**Comment by AnibalFlores** [comment]
Ya se hizo un Initial commit con la implementacion pero falta el detalle del total de paginas y el total de registros que probablemente lo incorpore con un helper y cuando este todo le agrego el postman, tampoco se aun como meter el manejo de tokens en swagger

**Comment by AnibalFlores** [comment]
Commit final se agregaron el total de elementos y de paginas y además uri para botones de primero anterior siguiente y último

**Comment by Alexx73** [comment]
testeado, Ok

**Comment by AnibalFlores** [comment]
merge a develop
