### ISSUE TITLE
TK#004: Prototipado de pantallas

### ISSUE THREAD

**Issue by AnibalFlores** [classroomEntreRios/proyecto-g1b-proyecto-g1b#4]
Realizar diseño de UI, contemplando funcionalidad **fullresponsive**, pantallas de Inicio, login, registro, olvido de contraseña, landing (home usuarios), dashboard (home admin), y **LABM*** de usuarios, logo **Viajes 365** y paleta de colores a definir en otra tarjeta.
Queda a libertad del developer la eleccion de herramientas para el prototipado (Pencil, AdobeXD, etc.), los achivos resultantes (y editables en lo posible) deben alojarse en la carpeta **viajes365-documentos/diseños**.
***L**istado, **A**lta, **B**aja y **M**odificación (CRUD en inglés)

- [x] Pantalla de Inicio o bienvenida al sitio
- [x] Pantalla de login
- [x] Pantalla de registro de usuario
- [x] Pantalla de olvido de contraseña
- [x] Pantalla Landing o Home para usuario registrado
- [x] Pantalla Dashboard o tablero de control para administrador
- [x] Pantalla Listado de usuarios
- [x] Pantalla Crear/Editar usuario
- [x] Pantalla Borrar un usuario

**Comment by KatiaFr** [comment]
https://drive.google.com/file/d/1s7WLNIDyvCqdA4hctiB0Ryqexe5YxKW8/view?usp=drivesdk


Ejemplos de páginas para comparar y elegir

**Comment by rafagareis** [comment]
Se genera prototipo.
